# Vector Representation of Words/Documents
Considerando as bases de texto fornecidas, implemente as seguintes atividades, que correspondem a algumas tarefas comuns em um pipeline de pré-processamento de texto:

### Pre process text

In [13]:
import numpy as np

# import data 
iliad_path = "../data/the-Iliad-of-homer.txt"
with open(iliad_path, "r") as f:
    iliad = f.read()


from nltk import word_tokenize

def preprocess_text(corpus):
    tokens = word_tokenize(corpus)
    words = []
    for token in tokens:
        if(token.isalpha()):
            words.append(token)

    return  " ".join(words)

iliad_corpus = preprocess_text(iliad)

In [14]:
print(iliad_corpus)

project gutenberg etext of the iliad of homer done into english prose by andrew lang walter leaf and ernest myers copyright laws are changing all over the world be sure to check the laws for your country before redistributing these files please take a look at the important information in this header we encourage you to keep this file on your own disk keeping an electronic path open for the next readers do not remove this this should be the first thing seen when anyone opens the book do not change or edit it without written permission the words are carefully chosen to provide users with the information they need about what they can legally do with the texts welcome to the world of free plain vanilla electronic texts etexts readable by both humans and by computers since these etexts prepared by hundreds of volunteers and donations information on contacting project gutenberg to get etexts and further information is included below we need your donations presently contributions are only bei

## 1. Representação vetorial de textos.
Sua função deve extrair o vocabulário do Corpus e gerar vetores (com o tamanho do vocabulário) que representam cada texto considerando as seguintes abordagens:

### (a) One Hot Encode - Binária, onde cada posição dos vetores deve indicar se uma palavra ocorreu ou não em um texto;

In [16]:
import numpy as np

def one_hot_encode(corpus):
  token_index = {}
  counter = 0
  
  for considered_word in corpus.split():
    if considered_word not in token_index:
      token_index.update({considered_word : counter + 1}) 
      
      counter = counter + 1   

  max_length = max([len(sample.split()) for sample in corpus])
  
  results  = np.zeros(shape = (len(corpus),
                              max_length,
                              max(token_index.values()) + 1)) 
  
  for i, sample in enumerate(corpus): 
    for j, considered_word in list(enumerate(sample.split())):
      
      index = token_index.get(considered_word)
      
      results[i, j, index] = 1. 

  return results, token_index

def print_encoding_result(result, token_dict):
  print(f'Palavras únicas: {token_dict}')
  print(f'Tamanho do tensor: {result.shape}')
  print(f'Corpus após o enconding: {result}')

iliad_encoded, iliad_dict = one_hot_encode(iliad_corpus)
print_encoding_result(iliad_encoded, iliad_dict)


: 

In [15]:
# Exemplo mais simples
second_corpus = "Xuxa, a sasha fez xixi na cama"

second_encoded, second_dict = one_hot_encode(second_corpus)
print_encoding_result(second_encoded, second_dict)

Palavras únicas: {'X': 1, 'u': 2, 'x': 3, 'a': 4, ',': 5, 's': 6, 'h': 7, 'f': 8, 'e': 9, 'z': 10, 'i': 11, 'n': 12, 'c': 13, 'm': 14}
Tamanho do tensor: (30, 1, 15)
Corpus após o enconding: [[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.

### (b) One Hot Encode - Contagem, onde cada posição dos vetores deve indicar o número de vezes que uma palavra ocorreu no texto;

In [65]:
def frequency_encode(corpus):
    token_index = {}
    counter = 0

    # Build token index (vocabulary)
    for sample in corpus:                                      
        for considered_word in sample.split():
            if considered_word not in token_index:
                token_index[considered_word] = counter + 1  # Assign unique index to each word
                counter += 1

    # Create a tensor to hold word frequency encoding (num_samples, num_unique_words)
    results = np.zeros(shape=(len(corpus),
                              max(token_index.values()) + 1))

    # Perform frequency encoding
    for i, sample in enumerate(corpus):
        for considered_word in sample.split():
            index = token_index.get(considered_word)
            # Increment the frequency count for the word in the current sample
            results[i, index] += 1

    return results, token_index

# Apply frequency encoding to the Iliad corpus
iliad_frequency_encoded, iliad_frequency_dict = frequency_encode(iliad_corpus)
print_encoding_result(iliad_frequency_encoded, iliad_frequency_dict)


Palavras únicas: {'\ufeffthe': 1, 'project': 2, 'gutenberg': 3, 'etext': 4, 'of': 5, 'the': 6, 'iliad': 7, 'homer': 8, 'done': 9, 'into': 10, 'english': 11, 'prose': 12, 'by': 13, 'andrew': 14, 'lang,': 15, 'm.a.,': 16, 'walter': 17, 'leaf,': 18, 'litt.d.,': 19, 'and': 20, 'ernest': 21, 'myers,': 22, 'm.a.': 23, 'copyright': 24, 'laws': 25, 'are': 26, 'changing': 27, 'all': 28, 'over': 29, 'world,': 30, 'be': 31, 'sure': 32, 'to': 33, 'check': 34, 'for': 35, 'your': 36, 'country': 37, 'before': 38, 'redistributing': 39, 'these': 40, 'files!!!': 41, 'please': 42, 'take': 43, 'a': 44, 'look': 45, 'at': 46, 'important': 47, 'information': 48, 'in': 49, 'this': 50, 'header.': 51, 'we': 52, 'encourage': 53, 'you': 54, 'keep': 55, 'file': 56, 'on': 57, 'own': 58, 'disk,': 59, 'keeping': 60, 'an': 61, 'electronic': 62, 'path': 63, 'open': 64, 'next': 65, 'readers.': 66, 'do': 67, 'not': 68, 'remove': 69, 'this.': 70, 'should': 71, 'first': 72, 'thing': 73, 'seen': 74, 'when': 75, 'anyone': 76

In [66]:

second_corpus = ["Xuxa, a sasha fez xixi na cama"]

second_frequency_encoded, second_frequency_dict = frequency_encode(second_corpus)
print_encoding_result(second_frequency_encoded, second_frequency_dict)

Palavras únicas: {'Xuxa,': 1, 'a': 2, 'sasha': 3, 'fez': 4, 'xixi': 5, 'na': 6, 'cama': 7}
Tamanho do tensor: (1, 8)
Corpus após o enconding: [[0. 1. 1. 1. 1. 1. 1. 1.]]
